version: '2'

services:

  php:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    ## supervisor
    #command: /usr/local/bin/supervisor-run.sh
    ## nginx
    #command: /usr/local/bin/nginx-run.sh
    ## nrpe
    #command: /usr/local/bin/nrpe-run.sh
    ## cron
    #command: /usr/local/bin/cron-run.sh
    #volumes:
    #  - ./files/etc/cron.d/:/etc/cron.d/